version: '3.9'

services:
  web:
    build: .
    command: >
      sh -c "
        sleep 5 &&
        flask db upgrade &&
        gunicorn run:app --bind 0.0.0.0:8000 --timeout 120
      "
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recordsdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine

  worker:
    build: .
    command: celery -A app.celery worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres

volumes:
  pgdata:
